# Generated by Django 5.2.8 on 2025-11-17 09:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna_dj', models.IntegerField(help_text='Número de columna en la DJ 1949 (8-37)', unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_dato', models.CharField(default='Factor (8 decimales)', max_length=50)),
            ],
            options={
                'ordering': ['columna_dj'],
            },
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=255)),
                ('nemonico', models.CharField(help_text='Ej: COPEC', max_length=20, unique=True)),
                ('tipo_sociedad', models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(choices=[('ACN', 'Acciones'), ('CFI', 'Cuotas Fondos de Inversión'), ('CFM', 'Cuotas Fondos Mutuos')], default='ACN', max_length=3)),
                ('fecha_pago', models.DateField(db_index=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('numero_dividendo', models.PositiveIntegerField(default=0, help_text='N° del evento según el emisor')),
                ('secuencia', models.PositiveIntegerField(default=0, help_text='Identificador único de secuencia del archivo')),
                ('ejercicio_comercial', models.PositiveIntegerField(default=2024, help_text='Año comercial (Ej: 2023)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.emisor')),
            ],
            options={
                'unique_together': {('emisor', 'numero_dividendo', 'ejercicio_comercial')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_distribuido', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('monto_unitario_pesos', models.DecimalField(decimal_places=6, default=0, help_text='Monto $/Acción', max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='core.eventocorporativo')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCalificacionTributaria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('monto_total_distribuido', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('monto_unitario_pesos', models.DecimalField(decimal_places=6, default=0, help_text='Monto $/Acción', max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20)),
                ('ultima_modificacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('evento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.eventocorporativo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calificacion tributaria',
                'verbose_name_plural': 'historical calificacion tributarias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventoCorporativo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mercado', models.CharField(choices=[('ACN', 'Acciones'), ('CFI', 'Cuotas Fondos de Inversión'), ('CFM', 'Cuotas Fondos Mutuos')], default='ACN', max_length=3)),
                ('fecha_pago', models.DateField(db_index=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('numero_dividendo', models.PositiveIntegerField(default=0, help_text='N° del evento según el emisor')),
                ('secuencia', models.PositiveIntegerField(default=0, help_text='Identificador único de secuencia del archivo')),
                ('ejercicio_comercial', models.PositiveIntegerField(default=2024, help_text='Año comercial (Ej: 2023)')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('emisor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.emisor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical evento corporativo',
                'verbose_name_plural': 'historical evento corporativos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DetalleFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.calificaciontributaria')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conceptofactor')),
            ],
            options={
                'unique_together': {('calificacion', 'concepto')},
            },
        ),
    ]
