# Generated by Django 5.2.8 on 2025-12-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcalificaciontributaria',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=20),
        ),
    ]
